In [1]:
import pandas as pd, numpy as np, seaborn as sns, matplotlib.pyplot as plt

df = sns.load_dataset('titanic')
df.shape
df.to_csv('../data/titanic.csv', index=False)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [3]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [4]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
df.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [6]:
[(c, df[c].unique()[:6]) for c in df.columns if df[c].nunique() < 10]

[('survived', array([0, 1])),
 ('pclass', array([3, 1, 2])),
 ('sex',
  <StringArray>
  ['male', 'female']
  Length: 2, dtype: str),
 ('sibsp', array([1, 0, 3, 4, 2, 5])),
 ('parch', array([0, 1, 2, 5, 3, 4])),
 ('embarked',
  <StringArray>
  ['S', 'C', 'Q', nan]
  Length: 4, dtype: str),
 ('class',
  ['Third', 'First', 'Second']
  Categories (3, str): ['First', 'Second', 'Third']),
 ('who',
  <StringArray>
  ['man', 'woman', 'child']
  Length: 3, dtype: str),
 ('adult_male', array([ True, False])),
 ('deck',
  [NaN, 'C', 'E', 'G', 'D', 'A']
  Categories (7, str): ['A', 'B', 'C', 'D', 'E', 'F', 'G']),
 ('embark_town',
  <StringArray>
  ['Southampton', 'Cherbourg', 'Queenstown', nan]
  Length: 4, dtype: str),
 ('alive',
  <StringArray>
  ['no', 'yes']
  Length: 2, dtype: str),
 ('alone', array([False,  True]))]

In [7]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
df[['survived', 'alive']].head(10)

   survived alive
0         0    no
1         1   yes
2         1   yes
3         1   yes
4         0    no
5         0    no
6         0    no
7         0    no
8         1   yes
9         1   yes

In [9]:
pd.crosstab(df['survived'], df['alive'])

alive      no  yes
survived
0         549    0
1           0  342

В выборке есть колонки которые повоторяют информацию, в целом если это не целевые переменные то не особо страшно, но если да то вся модель ломается, пример survived и alive, если бы я обучал модель предсказывать выживет ли человек на 2 титанике то она бы сначала показывала бы 100% правильный ответ, ведь модель бы нашла закономерность alive - no => survived - 0 и наоборот, поэтому на нормальном испытании где заранее не известно выжил ли человек или нет она бы посыпалась. Важно удалять данные которые дублируют ответ.

In [10]:
df.groupby(df['deck'].isnull())['survived'].agg(['count', 'mean'])

       count      mean
deck
False    203  0.669951
True     688  0.299419

In [11]:
df.groupby(df['age'].isnull())['survived'].agg(['count', 'mean'])

       count      mean
age
False    714  0.406162
True     177  0.293785